services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdamWojs\EzPlatformLocationReference\ExpressionLanguage\ExpressionLanguage: ~

    AdamWojs\EzPlatformLocationReference\LimitedLocationService: ~

    AdamWojs\EzPlatformLocationReference\NamedReferences\NamedReferencesProvider: ~

    AdamWojs\EzPlatformLocationReference\NamedReferences\NamedReferencesProviderInterface:
        alias: AdamWojs\EzPlatformLocationReference\NamedReferences\NamedReferencesProvider

    AdamWojs\EzPlatformLocationReference\LocationReferenceResolver: ~

    AdamWojs\EzPlatformLocationReference\LocationReferenceResolverInterface:
        alias: AdamWojs\EzPlatformLocationReference\LocationReferenceResolver

    AdamWojs\EzPlatformLocationReference\ConfigResolver\LocationConfigResolver: ~

    AdamWojs\EzPlatformLocationReference\ConfigResolver\LocationConfigResolverInterface:
        alias: AdamWojs\EzPlatformLocationReference\ConfigResolver\LocationConfigResolver
